### ISSUE TITLE
check if the file is in the vendor dir

### ISSUE THREAD

**Issue by Preovaleo** [vaniocz/symlink-handler#1]
i think we need to limit the copy to file in the vendor dir
are you agree?

**Comment by maryo** [comment]
Not sure I understand. After re-reading your Symfony issue this script is probably not exactly what you wanted althrough it is related. Could you explain it more?

**Comment by maryo** [comment]
Or do you want just a limitation for that symlinked file/directory that it always has to be inside the vendor directory?

**Comment by Preovaleo** [comment]
Hello,

Yep, i'm not sure that i can read myself too sorry!
I mean your second answer:
Actually if you create a link to a conf file it can be a little dangerous.
(yes it need a big setup but ...)

**Comment by maryo** [comment]
Currently the source path is constructed by concatenating the vendor directory path and the path defined under the symlinks (extra.symlinks) key in composer.json. So yes, if someone wanted to symlink something from a different directory than "vendor" he could do it using something like "../../../../../etc/passwd". But since this configuration is always present in the root composer.json (symlinks of dependent packages are ignored) then it is not such an issue because this file is mostly written by the development team of the project. So not sure if limiting the directory worth it. But after more thinking about it I think it does.

So I will add this limitation then.

Maybe even something like filtering of file extensions could help. But then it is starting to complicate even more. I will think about it. Thanks for your feedback.

**Comment by Preovaleo** [comment]
Thank you,
